server:
  shutdown: graceful
spring:
  application:
    name: checkoutkata
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000
management:
  endpoints:
    health:
      probes:
        enabled: true
    web:
      exposure:
        include: loggers,health,info,prometheus
  health:
    group:
      readiness:
        include:
          - db
          - ping
      liveness:
        include:
          - ping
springdoc:
  api-docs:
    enabled: true         # GET /v3/api-docs
  swagger-ui:
    enabled: true         # GET /swagger-ui/index.html
    path: /swagger-ui
    urls:
      - name: All
        url: /v3/api-docs
      - name: Checkout
        url: /v3/api-docs/checkout
      - name: Admin
        url: /v3/api-docs/admin
  server-url: ${PUBLIC_BASE_URL:localhost:8080}